<center>

# <b style="font-family: 'LUISS', 'Lato'">Data Processing</b>

<h2 style="font-family: 'LUISS', 'Lato'">Python and R for Data Science</h2>
<h3 style="font-family: 'LUISS', 'Lato'">Data Science and Management</h3>
<img src="https://ercoppa.github.io/labds/dist/img/cliente-luiss.png">
<br><br><br>

</center>

<center>

<img src="https://ercoppa.github.io/labds/03/img/tweet-ds.png" width="750">

</center>

# Package `numpy`

## Why `numpy`?

In science, we often want to work on multidimensional data:
- one dimension: list or *array* (*an efficient list with fixed size*)
- two dimensions: matrix, also dubbed 2d-array
- three dimensions: 3d-array
- n dimensions: nd-array

In theory, we could just use lists and nest them, e.g.:


In [1]:
matrix = [[1, 2, 3], [4, 5, 6]] # 2x3 matrix
print(matrix[1][0]) # first element of second row

4


However, lists are not very efficient. Hence, when we have thousands of data values they can be quite slow and memory hungry. This why we may want to use `numpy`.

## What is `numpy`?

<center>

<img src="https://ercoppa.github.io/labds/03/img/numpylogo.svg">

</center>

`numpy` (Numerical Python) contains **multidimensional array data structures**, such as homogeneous N-dimensional nd-array and a large library of **functions that operate efficiently** on them.

Main difference with Python lists:
- a `numpy` nd-array must contain values of the same numerical type
- a `numpy` nd-array has a fixed size
- a `numpy` nd-array should have a shape that is *rectangular*, i.e., different rows must have the same number of columns

## `numpy`: installation and import

Install `numpy` with `pip`:

In [2]:
! pip install numpy

By convention `numpy` is imported with an alias `np`:

In [3]:
import numpy as np
# now we can use numpy using np

## `numpy` array: construction

We can build an array by passing a list:

In [4]:
a1 = np.array([1, 2, 3])              # 1D array
print(a1)
a2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
print(a2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


For our goals, we often get the `numpy` arrays built from other packages, e.g., as a result of a complex data processing.

## `numpy` array: construction (cont'd)

`numpy` comes with many useful constructors:

In [5]:
a3 = np.zeros((2, 3)) # 2x3 array of zeros
print("Zeros:", a3)
a4 = np.ones((2, 3))  # 2x3 array of ones
print("Ones:", a4)
a5 = np.random.random((2, 3)) # 2x3 array of random numbers
print("Random:", a5)
a6 = np.empty((2, 3)) # 2x3 array of numbers already in memory
print("Garbage:", a6) # this is used when we do not care
                      # for the values of the array
                      # but they are guaranteed to be random!

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Random: [[0.95422938 0.0715618  0.74741131]
 [0.68029107 0.1118279  0.23359043]]
Garbage: [[0.95422938 0.0715618  0.74741131]
 [0.68029107 0.1118279  0.23359043]]


## `numpy` array: construction (cont'd)

We can build arrays according to a range or a linearly spaced criteria:

In [6]:
a7 = np.arange(0, 10, 2) # array of numbers from 0 to 10 with step 2
print("Range:", a7)

a8 = np.linspace(1, 10, 5)  # array of 5 numbers
                            # from 1 to 10
                            # linearly spaced
print("Linspace:", a8)

Range: [0 2 4 6 8]
Linspace: [ 1.    3.25  5.5   7.75 10.  ]


## `numpy` array: data type

Be default, a `numpy` array uses floating-point values. However, we can set the `numpy` data type during construction:

In [7]:
a = np.ones(2, dtype=np.dtype('int')) # 1D array of ones with int type
print(a)

[1 1]


Since `numpy` is used to efficiently perform scientific computations, it comes with a wide range of `numpy` data types, that goes beyond the Python types `int`, `float`, `bool`, and `str`. For instance, it supports complex numbers or *smaller* integers (which require less memory but are less accurate).

When using `numpy`, for our goals, we can stick with `np.dtype('int')` and `np.dtype('float')` types.

## `numpy` array is similar to a list

Similarly to lists, we can:

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
print("array:", a)
print("element:", a[0])     # access an element
print("slice:", a[1:3])     # access a slice
print("A slice is still an numpy array:", type(a[1:3]))

a[0] = 10                   # modify an element
print("Updated array:", a)

a = np.array([[1, 2, 3], [4, 5, 6]])            # 2x3 array
print("element:", a[1, 0], "same as", a[1][0])  # first element of second row
a[0] = 10                                       # modify the first row
print("Updated 2D array:", a)

array: [1 2 3 4 5 6]
element: 1
slice: [2 3]
A slice is still an numpy array: <class 'numpy.ndarray'>
Updated array: [10  2  3  4  5  6]
element: 4 same as 4
Updated 2D array: [[10 10 10]
 [ 4  5  6]]


## `numpy` array: attributes

A few useful attributes:

In [9]:
a = np.random.random((2, 3))            # random 2x3 array
print("Data type:", a.dtype)            # data type of the array
print("Shape:", a.shape)                # shape of the array
print("Size:", a.size)                  # number of elements in the array
print("Number of dimensions:", a.ndim)  # number of dimensions

Data type: float64
Shape: (2, 3)
Size: 6
Number of dimensions: 2


## `numpy` array: operations

Given `a1 = np.array([[1, 2], [4, 5]])` and `a2 = np.array([[6, 7], [8, 9]])`:

| Operator | Semantics | Example | Example Result |
| -------- | ------- | :-------: | :-------: |  
| `+` | element-wise sum |`a1 + a2` | `[[ 7  9] [12 14]]`| 
| `-` | element-wise difference |`a1 - a2` | `[[-5 -5] [-4 -4]]`| 
| `*` | element-wise product |`a1 - a2` | `[[ 6 14] [32 45]]`| 
| `/` | element-wise division |`a1 / a2` | `[[0.16 0.28] [0.5 0.55]]`|
| `%` | element-wise remainder |`a2 % a1` | `[[ 1  4] [16 25]]`| 
| `**` | element-wise exp |`a1**2` | `[[ 6 14] [32 45]]`| 
| `np.dot()` | matrix product |`np.dot(a1, a2)` | `[[22 25] [64 73]]`| 
| `a1.min()` | minimum value |`a1.min()` | `1`|
| `a1.max()` | maximum value |`a1.max()` | `5`|
| `a1.sum()` | sum of values |`a1.sum()` | `12`| 

## `numpy` array: try them!

In [10]:
a1 = np.array([[1, 2], [4, 5]])
a2 = np.array([[6, 7], [8, 9]])
print("Sum:", a1 + a2)          # element-wise sum
print("Difference:", a1 - a2)   # element-wise difference
print("Product:", a1 * a2)      # element-wise product
print("Division:", a1 / a2)     # element-wise division
print("Module:", a2 % a1)       # element-wise module
print("Power:", a1 ** 2)        # element-wise power
print("Matrix product:", np.dot(a1, a2)) # matrix product
print("Matrix product:", a1.dot(a2))     # matrix product
print("Min:", a1.min())         # minimum element
print("Max:", a1.max())         # maximum element
print("Sum:", a1.sum())         # sum of all elements

Sum: [[ 7  9]
 [12 14]]
Difference: [[-5 -5]
 [-4 -4]]
Product: [[ 6 14]
 [32 45]]
Division: [[0.16666667 0.28571429]
 [0.5        0.55555556]]
Module: [[0 1]
 [0 4]]
Power: [[ 1  4]
 [16 25]]
Matrix product: [[22 25]
 [64 73]]
Matrix product: [[22 25]
 [64 73]]
Min: 1
Max: 5
Sum: 12


## `numpy` array: concatenation and sorting

We cannot extend an existing `numpy` array but we can concanate arrays:

In [11]:
a1 = np.array([3, 1, 2])
a2 = np.array([4, 6, 5])
a3 = np.concatenate([a1, a2]) # concatenate two arrays
print("Concatenated:", a3)

Concatenated: [3 1 2 4 6 5]


We can get a new sorted version of an array:

In [12]:
a4 = np.sort(a1)
print("Sorted:", a4)

Sorted: [1 2 3]


## `numpy` array: filtering

We can easily filter values:

In [13]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array:", a)
print("Filtered array (less than 6):", a[a < 6])        # elements less than 6
print("Filtered array (even):", a[a % 2 == 0])          # even elements
print("Filtered array (and):", a[(a > 2) & (a < 11)])   # conjunction of two conditions
print("Filtered array (or):", a[(a < 2) | (a > 10)])    # disjunction of two conditions
print("Check conditions:", (a > 5) | (a == 5))          # check conditions    

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Filtered array (less than 6): [1 2 3 4 5]
Filtered array (even): [ 2  4  6  8 10 12]
Filtered array (and): [ 3  4  5  6  7  8  9 10]
Filtered array (or): [ 1 11 12]
Check conditions: [[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


## `numpy` array: `nonzero()`

A convenient function is `nonzero()` that:
- takes an array
- returns one array for each dimension containing the index of elements that are different than zero

In [14]:
a = np.array([[-1, -2, -3, -4], [5, 6, 7, 8], [9, 10, 11, 12]])
nonzero_a_idx = np.nonzero(a) # default condition: a != 0
print("Indexes of non-zero elements:", np.nonzero(a))
print("Non-zero elements:", a[nonzero_a_idx])


Indexes of non-zero elements: (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
Non-zero elements: [-1 -2 -3 -4  5  6  7  8  9 10 11 12]


## `numpy` array: `nonzero()` (cont'd)

However, instead of checking for the nonzero condition, we can pass an arbitrary condition:

In [15]:

g10_a_idx = np.nonzero(a > 10) # condition: a > 10
print("Indexes of condition > 10:", g10_a_idx)
print("> 10 elements:", a[g10_a_idx])


Indexes of condition > 10: (array([2, 2]), array([2, 3]))
> 10 elements: [11 12]


## `numpy`: `nan` value

`numpy` devises a constant for a represeting *invalid* (**N**ot **A** **N**umber) or *missing* value:

In [16]:
print("NaN:", np.nan) # Not a Number

NaN: nan


We will meet it quite often in the real world...

## `numpy`: documentation

There is ***way more*** to say about `numpy`. Check its documentation:

- [Getting started](https://numpy.org/doc/stable/user/index.html#user)
- [API reference](https://numpy.org/doc/stable/reference/index.html#reference)

We will cover other bits of it when needed.

# Tabular Data and Tidy Data

## Tabular Data?

<center>

<img src="https://ercoppa.github.io/labds/03/img/tabular-data-mess.png" width="850">

</center>

Same data, 3 different ways of arranging it in a table!

We have **three** *variables*, **six** *observations*, and **18** (17 non null) values (*measurements*)

## **Tidy Data**: make tabular data actionable

<center>

<img src="https://ercoppa.github.io/labds/03/img/tidydata.png" width="850">

</center>

## Tidy Data: variables, observations, and values

<center>

<img src="https://ercoppa.github.io/labds/03/img/tidydata-2.png" width="850">

</center>

## Tidy Data: still a mess...

<center>

<img src="https://ercoppa.github.io/labds/03/img/tidydata-3.png" width="850">

</center>

<center>
<a src="https://openscapes.org/blog/2020-10-12-tidy-data">Image credits</a>
</center>

## Tidy Data: ...but a processable mess!

<center>

<img src="https://ercoppa.github.io/labds/03/img/tidydata-4.png" width="850">

</center>

<center>
<a src="https://openscapes.org/blog/2020-10-12-tidy-data">Image credits</a>
</center>

## Tidy Data: long form

Tidy Data favors the long form (left) instead of the wide form (right):

<center>

<img src="https://ercoppa.github.io/labds/03/img/tidydata-5.png" width="850">

</center>

However, the long form is often more convenient when processing data, while the wide form could be more convenient when visualizing the data in plots. We will have to reshape our data when needed.

# Package `pandas`

## Why do we need `pandas`?

Two key reasons:
- tabular data
- data science oriented

Often we look at a dataset as a matrix, i.e., **tabular data**. `pandas` is built on top of `numpy` providing a large amount of functionalities that are quite convenient in the presence of tabular data. 

Also, `numpy` offers quite low-level abstractions, without directly supporting construction from popular data formats and common data science analyses.

All these additional features come with a performance cost: `pandas` can be slower than `numpy`.

## What is `pandas`?

<center>

<img src="https://ercoppa.github.io/labds/03/img/pandas-logo.png" width="300">

</center>

`pandas` is a (reasonably) fast, powerful, flexible and easy to use open source **data analysis and manipulation framework**, built on top of the Python programming language. In particular, it offers two main data structures:

- `pandas.Series`: 1d-array
- `pandas.DataFrame`: 2d-array

It internally exploits `numpy` but gives a **higher-level abstraction** compared to `numpy.array`, making it easier to solve a large number of tasks. Moreover, it offers compatibility with several data formats.

***It is a reference library in the data science field and you have to master it.***

<center>

<img src="https://ercoppa.github.io/labds/03/img/meme-pandas.webp" width="750">

</center>

## `pandas`: installation and import

We can install it with `pip`:

In [17]:
! pip install pandas

By convention, the community often import it in the code with the alias `pd`:

In [18]:
import pandas as pd
import numpy as np # we often use numpy with pandas

## `pandas.Series`: construction

A `pandas.Series` represent a sequence, or series, of values. We can see it as a ***one-dimensional data structure***, containing values of the same data type. 

We can build it from most iterable data structure:

In [19]:
s0 = pd.Series([0, 9, 3])
print("Series:", s0)

Series: 0    0
1    9
2    3
dtype: int64


When printing it, we see that each value has (as expected!) an index. The series stores values of a specific data type (which is consistent with `numpy.dtype`), which, optionally, can be specified at contruction time:

In [20]:
print(pd.Series([1, 2, 3], dtype=np.dtype('float'))) # float series

0    1.0
1    2.0
2    3.0
dtype: float64


## `pandas.Series`: construction (cont'd)

Differently from `numpy.array`, a `pandas.Series` can have custom index labels:

In [21]:
s1 = pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])
print("Series with labels:", s1)

Series with labels: a    1
b    2
c    3
d    4
dtype: int64


While this is nothing special (we could reproduce it with `numpy` by keeping a dictionary between labels and index values), it is quite convienient as it makes everything more intuitive and reabable.

If want to have the same value for all indexes:

In [22]:
pd.Series(2.0, index=['a', 'b', 'c', 'd'])

a    2.0
b    2.0
c    2.0
d    2.0
dtype: float64

## `pandas.Series` vs Python dictionary

Since we can have custom labels, then this means that a `pandas.Series` is not that different from a Python dictionary. Indeed, we can build it from a dictionary:

In [23]:
s1 = pd.Series({'a': 1, 'b': 2})
print("Series with labels:", s1)

Series with labels: a    1
b    2
dtype: int64


However, a `pandas.Series` can have duplicated index labels:

In [24]:

s1 = pd.Series([1,2,3], index=['a', 'b', 'b'])
print("Series with duplicated index labels:", s1)

Series with duplicated index labels: a    1
b    2
b    3
dtype: int64


while **dictionaries cannot contain the same key twice**!

## `pandas.Series`: indexing

We can use index labels to get element(s):

In [25]:
s0 = pd.Series([8,22,33])
print("Series:", s0)
print("Value from positional index:", s0[1], "\n")

s1 = pd.Series([18,122,133], index=['a', 'b', 'c'])
print("Series:", s1)
print("Value from index label:", s1['b'])


Series: 0     8
1    22
2    33
dtype: int64
Value from positional index: 22 

Series: a     18
b    122
c    133
dtype: int64
Value from index label: 122


## `pandas.Series`: indexing (cont'd)

Indexing may lead to multiple values in the case of duplicated index labels:

In [26]:
s2 = pd.Series([18,122,133], index=['a', 'b', 'b']) # duplicate index label!
print("Series:", s2, "\n")
print("Multiple values from index label", s2['b'], "\n")

Series: a     18
b    122
b    133
dtype: int64 

Multiple values from index label b    122
b    133
dtype: int64 



## `pandas.Series`: slicing

Slicing is supported:

In [27]:
s0 = pd.Series([8,22,33])
print("Slicing with positional indexes:", s0[:1]) # or s0.loc[:1]


Slicing with positional indexes: 0    8
dtype: int64


When we use index labels, we can still perform slicing:

In [28]:

s1 = pd.Series([18,122,133,155], index=['a', 'b', 'b', 'c'])
print("\nSlicing with index labels:")
print(s1.loc[:'b']) # both 'b' values are included


Slicing with index labels:
a     18
b    122
b    133
dtype: int64


## `pandas.Series`: attributes

A few interesting attributes:

In [29]:
s1 = pd.Series([1,2,3], index=['a', 'b', 'b'])
print("Indexes:", s1.index)
print("Values:", s1.values)
print("Data type:", s1.dtype)
print("Size:", s1.size)
print("Shape:", s1.shape)

Indexes: Index(['a', 'b', 'b'], dtype='object')
Values: [1 2 3]
Data type: int64
Size: 3
Shape: (3,)


## `pandas.Series` contains a `numpy.ndarray`

We can always get the internal `numpy.ndarray` used by `pandas.Series` to store the values:

In [30]:
s1 = pd.Series([1,2,3], index=['a', 'b', 'b'])
print("Internal array:", s1.array)

Internal array: <NumpyExtensionArray>
[np.int64(1), np.int64(2), np.int64(3)]
Length: 3, dtype: int64


`NumpyExtensionArray` is a thin layer around `pandas.ndarry`. If you want to get exaclty a `pandas.ndarray` then:

In [31]:
print("Internal numpy array:", s1.to_numpy(), "of type", type(s1.to_numpy()))

Internal numpy array: [1 2 3] of type <class 'numpy.ndarray'>


***The positive consequence is that anything supported by `numpy.ndarray` workd also over `pandas.Series`. For instance, all element-wise operations or aggregate functions (e.g., min, max, sum) works as expected.***

## `pandas.DataFrame`: informal definition

A `pandas.DataFrame` represents ***tabular data***, i.e., two-dimensional data structure. In this matrix representation:
- columuns have a label/name
- each column is a... `pandas.Series`

Being designed for tabular data, it fits very well with several data formats handling tabular data, such as:
- `CSV`
- `TSV`
- `XLSX`


## `pandas.DataFrame`: construction from dictionary

We can build it from a dictionary:

In [32]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Country': ['USA', 'Canada', 'Australia', 'UK']
}
df = pd.DataFrame(data)
df # jupyter will display the dataframe in nice way
   # if you put its variable as the last line of the cell

Name  Age    Country
0    Alice   25        USA
1      Bob   30     Canada
2  Charlie   35  Australia
3    David   40         UK

Notice that each key-value pair becomes a different column, where the key is the name of the column and the values the column values. To make this consistents, the values in the dictionary should be iterable and have the same length.

## `pandas.DataFrame`: construction from CSV

We can build a `pandas.Dataframe` from a (local or remote) CSV:

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
col_names = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Class']
pd.read_csv(url, names=col_names) # the CSV does not have a header, we provide it.

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

## `pandas.DataFrame`: construction from popular data formats

A `pandas.DataFrame` can be built (converted) from (to) several popular data formats:

| Type | Format | Reader | Writer|
| :--: | :--: | :--: | :--: |
| text | CSV | `read_csv` | `to_csv` |
| text | TSV | `read_csv(..., sep='\t')` | `to_csv(..., sep='\t')` |
| binary | XSLX | `read_excel` | `to_excel` |
| text | JSON | `read_json` | `to_json` |
| text | SQL | `read_sql` | `to_sql` |

But the list is larger: [supported data formats](https://pandas.pydata.org/docs/user_guide/io.html#io-tools-text-csv-hdf5)

Some of these data formats are not designed for tabular data, e.g., JSON. <br>
Hence, we have to give insight to `pandas` on how to extract the tabular data from them!



## `pandas.DataFrame`: basic attributes

In [34]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30], 'Country': ['USA', 'Canada']}
df = pd.DataFrame(data)
print("DataFrame index:", df.index)
print("DataFrame columns:", df.columns)
print("DataFrame shape:", df.shape)
print("DataFrame size:", df.size) # number of elements wrt all columns
print("\nDataFrame data type:\n%s" % df.dtypes)
print("\nDataFrame values:\n%s" % df.values)


DataFrame index: RangeIndex(start=0, stop=2, step=1)
DataFrame columns: Index(['Name', 'Age', 'Country'], dtype='object')
DataFrame shape: (2, 3)
DataFrame size: 6

DataFrame data type:
Name       object
Age         int64
Country    object
dtype: object

DataFrame values:
[['Alice' 25 'USA']
 ['Bob' 30 'Canada']]


## `pandas.DataFrame`: cumulative info

In [35]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30], 'Country': ['USA', 'Canada']}
df = pd.DataFrame(data)
print("DataFrame info:\n%s" % df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     2 non-null      object
 1   Age      2 non-null      int64 
 2   Country  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes
DataFrame info:
None


## `pandas.DataFrame`: sampling

Printing the entire `DataFrame` can be inefficient, hence we can get a sample out of it:

In [36]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30], 'Country': ['USA', 'Canada']}
df = pd.DataFrame(data)
df.head(n=1) # first n row(s)

Name  Age Country
0  Alice   25     USA

In [37]:
df.tail(n=1) # last n row(s)

Name  Age Country
1  Bob   30  Canada

In [38]:
df.sample(n=1) # random n row(s)

Name  Age Country
0  Alice   25     USA

## `pandas.DataFrame`: select rows

We can easily obtain a row:

In [39]:
data = {'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']}
df = pd.DataFrame(data)
print(df.loc[1])    # we ask for a single row
print("result type:", type(df.loc[1]))

Name       Bob
Age         30
Country     CA
Name: 1, dtype: object
result type: <class 'pandas.core.series.Series'>


Or a subsequence of the rows:

In [40]:
print("result type for a slice:", type(df.loc[1:2]))
df.loc[1:2]

result type for a slice: <class 'pandas.core.frame.DataFrame'>


Name  Age Country
1   Bob   30      CA
2  Carl   35      US

## `pandas.DataFrame`: select columns

We can easily obtain a column:

In [41]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
print(df['Name'])
print("result type:", type(df['Name']))

0    Alice
1      Bob
2     Carl
Name: Name, dtype: object
result type: <class 'pandas.core.series.Series'>


Or, a subset of columns:

In [42]:
print("result type:", type(df[['Name', 'Age']]))
df[['Name', 'Age']] # list of the columns we want back

result type: <class 'pandas.core.frame.DataFrame'>


Name  Age
0  Alice   25
1    Bob   30
2   Carl   35

## `pandas.DataFrame`: filtering rows

When selecting columns, we can also apply filtering criteria over the rows:

In [43]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
df.loc[df['Age'] > 25] # df filtered by the condition 'Age' > 25

Name  Age Country
1   Bob   30      CA
2  Carl   35      US

In [44]:
df.loc[df['Age'] > 25, 'Name'] # we ask for the 'Name' column of the rows where 'Age' > 25

1     Bob
2    Carl
Name: Name, dtype: object

In [45]:
df.loc[(df['Age'] > 25) & (df['Country'] == 'US'), 'Name'] # two filtering conditions then select col

2    Carl
Name: Name, dtype: object

## `pandas.DataFrame`: update an element

We can update a specific element:

In [46]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
df.loc[0, 'Name'] = 'David' # change the value of the first row and 'Name' column
# df.at[0, 'Name'] = 'Alice' # same as above
df

Name  Age Country
0  David   25      US
1    Bob   30      CA
2   Carl   35      US

## `pandas.DataFrame`: update a column

We can even update an entire column:

In [47]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
df['Age'] = -1
df

Name  Age Country
0  Alice   -1      US
1    Bob   -1      CA
2   Carl   -1      US

We can perform functional updates:

In [48]:
df['Age'] = df['Age'] + 20
df['Country'] = df['Country'].replace('US', 'USA')  
df

Name  Age Country
0  Alice   19     USA
1    Bob   19      CA
2   Carl   19     USA

## `pandas.DataFrame`: append row(s)

Incrementally appending rows is **inefficient** since the underlying `pandas.Series` has a fixed size, making expensive the update. However, it can be done:

In [49]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
df2 = pd.concat([df, pd.DataFrame({'Name': ['David', 'Eve'], 'Age': [40, 45], 'Country': ['UK', 'AU']})], ignore_index=True)
df2

Name  Age Country
0  Alice   25      US
1    Bob   30      CA
2   Carl   35      US
3  David   40      UK
4    Eve   45      AU

## `pandas.DataFrame`: append columns

We can add columns:

In [50]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
df['Gender'] = ['F', 'M', 'M']
df['Salary'] = np.nan
df

Name  Age Country Gender  Salary
0  Alice   25      US      F     NaN
1    Bob   30      CA      M     NaN
2   Carl   35      US      M     NaN

## `pandas.DataFrame`: sorting rows

Sorting:

In [51]:
df = pd.DataFrame({'Name': ['Alice', 'Carl', 'Bob'], 'Age': [25, 35, 35], 'Country': ['US', 'CA', 'US']})
df.sort_values(['Age', 'Name'], ascending=False)

Name  Age Country
1   Carl   35      CA
2    Bob   35      US
0  Alice   25      US

## Data cleaning: dropping *invalid* rows

Suppose we get this `DataFrame`:

In [52]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
df['Salary'] = [100, np.nan, 300]
df

Name  Age Country  Salary
0  Alice   25      US   100.0
1    Bob   30      CA     NaN
2   Carl   35      US   300.0

To clean our `DataFrame`, we may want to **drop rows with invalid values**, i.e., `np.nan`. Indeed, `np.nan` would likely invalidate most computations (e.g., computing the average). **Notice that dropping rows will make us lose (potentially valuable) information**. If you want to still do it, we can do:

In [53]:
df.dropna() # drop rows with NaN values

Name  Age Country  Salary
0  Alice   25      US   100.0
2   Carl   35      US   300.0

## Data cleaning: using *default* value

Again, assume we get this `DataFrame`:

In [54]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Carl'], 'Age': [25, 30, 35], 'Country': ['US', 'CA', 'US']})
df['Salary'] = [100, np.nan, 300]
df

Name  Age Country  Salary
0  Alice   25      US   100.0
1    Bob   30      CA     NaN
2   Carl   35      US   300.0

As an alternative strategy for data cleaning, we opt to define a default value in place of invalid values:

In [55]:
value = 60
df.fillna(value) # fill NaN values with a specific value

Name  Age Country  Salary
0  Alice   25      US   100.0
1    Bob   30      CA    60.0
2   Carl   35      US   300.0

## `pandas.DataFrame`: cumulative statistics

We can quickly compute some raw statistics:

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
col_names = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Class']
df = pd.read_csv(url, names=col_names) # the CSV does not have a header, we provide it.
df.describe()


Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## `pandas` can do way more...

Besides the official documentation:

<center>
<a href="https://pandas.pydata.org/docs/index.html">https://pandas.pydata.org/docs/index.html</a>
</center>

There is a nice *cheatsheet* from the community that compactly summarize the functionalities:

<center>

<img src="https://ercoppa.github.io/labds/03/img/pandas-cheatsheet-0.png" width="400">

</center>

<center>
<b>Available at <a href="https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf">https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf</a></b>
</center>

## `pandas` cheatsheet: reshaping

<center>

<img src="https://ercoppa.github.io/labds/03/img/pandas-cheatsheet-1.png" width="950">

</center>

## `pandas` cheatsheet: summary functions

<center>

<img src="https://ercoppa.github.io/labds/03/img/pandas-cheatsheet-2.png" width="400">

</center>

## `pandas` cheatsheet: group data

<center>

<img src="https://ercoppa.github.io/labds/03/img/pandas-cheatsheet-3.png" width="900">

</center>

## `pandas` cheatsheet: merge

<center>

<img src="https://ercoppa.github.io/labds/03/img/pandas-cheatsheet-4.png" width="360">

</center>